In [45]:
import numpy as np

In [46]:
a2 = np.array([
    [1,2,3.3],
    [4,5,6.6]
])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [47]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

### 8) Comparison Operators for numpy arrays

In [48]:
a1 > a2 # will return another ndarray - tells us if each element in a1
# is greater than each element in a2

array([[False, False, False],
       [False, False, False]])

In [49]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [50]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [51]:
a1 > 5

array([False, False, False])

In [52]:
a1 < 5

array([ True,  True,  True])

In [53]:
a1 == a1

array([ True,  True,  True])

In [54]:
a1 == a2 # if each element in a1 == each element in a2

array([[ True,  True, False],
       [False, False, False]])

In [55]:
# there are more in numpy documentation, but these are the main ones

In [56]:
# --------------------------------------------------------

### 9) Sorting Arrays

In [57]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[4, 4, 0, 7, 3],
       [2, 7, 4, 0, 1],
       [9, 4, 2, 4, 5]])

In [58]:
np.sort(random_array)

array([[0, 3, 4, 4, 7],
       [0, 1, 2, 4, 7],
       [2, 4, 4, 5, 9]])

In [59]:
# return the indices that would sort an array
# sort the indices
np.argsort(random_array)

array([[2, 4, 0, 1, 3],
       [3, 4, 0, 2, 1],
       [2, 1, 3, 4, 0]], dtype=int64)

In [60]:
# get the index which contains min value
np.argmin(random_array)

2

In [61]:
np.argmax(random_array)

10

In [62]:
# get the index which contains max value
np.argmax(random_array, axis=0)

array([2, 1, 1, 0, 2], dtype=int64)

In [63]:
# 2d array
# axis = 0 --> go down vertically
# axis = 1 --> go down horizantally

In [64]:
# ---------------------------------------------------

### Practical example - Turn Images into Numpy Arrays

### Numpy Array Iterating

In [65]:
# Iterating means going through elements one by one

# default datatype of numpy array(ndarray) is float

In [66]:
a1

array([1, 2, 3])

In [67]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [68]:
# 1D array
for i in a1:
    print(i, end=" ")

1 2 3 

In [69]:
# 2D array
# go through all the rows
for i in a2:
    print(i, end=" ")

[1.  2.  3.3] [4.  5.  6.6] 

In [70]:
# 2D array
# go through each element in 2D
for i in a2:
    for j in i:
        print(j, end=" ")
    print()

1.0 2.0 3.3 
4.0 5.0 6.6 


In [71]:
# -------------------------------------

### Joining Array

In [72]:
# putting contents of two or more arrays into one single array

# the numpy arrays are joined by axis
# if axis is not mentioned, it is taken as 0
# 1d, axis = 0 by default
a1

array([1, 2, 3])

In [73]:
a3 = np.array([4,5,6])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [76]:
a_combine = np.concatenate((a1,a3))
a_combine

array([1, 2, 3, 4, 5, 6])

In [75]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [77]:
a4 = np.array([
    [6,8,7.8],
    [3,4,4.3]
])
a4

array([[6. , 8. , 7.8],
       [3. , 4. , 4.3]])

In [79]:
arr = np.concatenate((a2,a4),axis=1)
arr

array([[1. , 2. , 3.3, 6. , 8. , 7.8],
       [4. , 5. , 6.6, 3. , 4. , 4.3]])

### Spliting Array

In [88]:
# splitting breaks one array into multiple
# array_split()

In [89]:
# split original array into 3 arrays
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [92]:
newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [93]:
newarr[0]

array([1, 2])

In [94]:
newarr[1]

array([3, 4])

In [95]:
newarr[2]

array([5, 6])

In [96]:
# same syntax for 2D array

### Searching Array

In [98]:
# search the array for a certain value, return the index at which a match occurs

In [99]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [102]:
# find index where value 4 is present
x = np.where(arr == 4)
x

(array([3], dtype=int64),)

In [103]:
# find index where values are even
x = np.where(arr%2==0)
x

(array([1, 3, 5], dtype=int64),)

In [104]:
# searchsorted() performs binary search in the array, and returns the index where the specified value would be inserted
# searchsorted() method is assumed to be used on sorted arrays
a7 = np.array([4,5,9,2,10,1,6])
a7

array([ 4,  5,  9,  2, 10,  1,  6])

In [106]:
a8 = np.sort(a7)
a8

array([ 1,  2,  4,  5,  6,  9, 10])

In [108]:
indx = np.searchsorted(a8, 7)
indx

5

In [ ]:
# so 7 should be inserted into index 5 in order to maintain a sorted order