In [4]:
import numpy as np
import pandas as pd

## 2) Slicing Arrays

creating sub-arrays from array

In [2]:
# Negative indexing --> Access an array from end

In [48]:
arr = np.array([1,2,2,5,5,6,9,8])
arr[-1]

8

In [5]:
# Slicing arrays

# [start:end:step], step initially = 1

In [6]:
# slice from index 1 to 3 (not included)
arr[1:3]
# stops at end-1

array([2, 3])

In [7]:
# slice from index 2 to end of array
arr[2:]

array([3, 4, 5])

In [8]:
# slice from beginning to index 3
arr[:3]

array([1, 2, 3])

In [9]:
# Slicing 2D arrays

In [12]:
arr2[0, 1:4]
# from first row, slice from index 1 to 4 (not included)

array([2, 3, 4])

In [13]:
# from both rows, return index 2
arr2[0:2, 2]

array([3, 8])

In [14]:
# return a 2d array from slicing
arr2[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [25]:
# reverse an array
arr[::-1]

array([5, 4, 3, 2, 1])

### 3) Creating Arrays

In [5]:
# Placeholder arrays --> to keep initial values

# np.zeros() --> return a new array filed with 0s
# ,and np.ones() return a new array filed with 1s

In [6]:
zeros = np.zeros((2,3))
# the array will have 2 dimensions, each 3 elements
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones = np.ones(3,)
ones
# 1 dimension, with 3 elements

array([1., 1., 1.])

In [8]:
# Shift + tab --> open up function docstring from documentation

# arange(start,stop,step) = Create an array within a range of values
 
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [17]:
# Fill an array with random integers

# random.randint(low,high,size)
random_array_2d = np.random.randint(0,10,size=(3,5))

random_array_2d # 3 rows, 5 cols

array([[5, 1, 1, 2, 7],
       [0, 7, 1, 2, 2],
       [2, 2, 8, 1, 6]])

In [10]:
random_array_2d.size

15

In [11]:
random_array_2d.shape

(3, 5)

In [12]:
random_array = np.random.randint(0,10, size=(1,5))
random_array # 1d, 5 elements

array([[5, 8, 3, 6, 1]])

In [13]:
random_array_2 = np.random.random((5, 3))
# generates floating numbers between 0.0 - 1.0
# size = (5,3), i.e. 5 rows, 3 cols
random_array_2

array([[0.27677592, 0.70826555, 0.08577419],
       [0.48089639, 0.71222076, 0.6321143 ],
       [0.66164426, 0.3188512 , 0.61689128],
       [0.53442974, 0.74029995, 0.08329263],
       [0.62411571, 0.43663984, 0.11793457]])

In [14]:
# similar to above
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.63569199, 0.19695445, 0.26310851],
       [0.13453928, 0.20006762, 0.8769305 ],
       [0.50765981, 0.13160756, 0.41561243],
       [0.90522816, 0.43550697, 0.50577461],
       [0.74759013, 0.00376786, 0.31134312]])

### Numpy Random Seed

In [15]:
# Pseudo-random numbers
# np.random.seed()

# NumPy uses pseudo-random numbers, which means, the numbers look random 
# but are re-producable ---> closer to the seed

In [19]:
# With np.random.seed() set, every time you run the cell above, the same random numbers will be generated.

# What if np.random.seed() wasn't set?

# Every time you run the cell below, a new set of numbers will appear.

In [32]:
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(1,5))
random_array_4

array([[5, 0, 3, 3, 7]])

In [28]:
random_array_4.shape

(1, 5)

In [34]:
np.random.seed(7)
random_array_5 = np.random.random((3,4))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904]])

In [35]:
# --------------------------------------------------------------

In [37]:
# Generate a 1-D array containing 5 random integers from 0 to 100:
my_arr = np.random.randint(100, size=(5))
my_arr

array([19, 60, 44, 63, 69])

In [39]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
my_arr2 = np.random.randint(100, size=(3,5))
my_arr2

array([[67, 72, 83, 48,  1],
       [64, 16, 31, 93, 44],
       [92, 71, 23, 10, 35]])

In [41]:
# Generate a 1-D array containing 5 random floats:
my_arr3 = np.random.rand(5)
my_arr3

array([0.54723513, 0.31020924, 0.28271973, 0.92099354, 0.43334216])

In [42]:
# choice() method allows you to generate a random value based on an array of values.
# size parameter to specify the shape of the array.

In [45]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
my_arr4 = np.random.choice([3,5,7,9],size=(3,5))
my_arr4

array([[9, 9, 7, 9, 3],
       [3, 5, 9, 5, 5],
       [3, 9, 7, 7, 3]])

### More Numpy Random distributions

learn when needed (w3schools)
1) data distribution - probability
2) normal distribution
3) binomial distribution
4)poisson distribution
5) uniform distribution
6) exponential distribution
7) random permutation
8) seaborn module


### Find the unique elements of an array

In [52]:
# using np.unique(arr) - study from documentation or google search