In [1]:
import numpy as np
import pandas as pd

### 5) Manipulating & Comparing Arrays

### Arithmetic 

In [45]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [46]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [5]:
# addition
a1 + ones

array([2., 3., 4.])

In [6]:
# subtraction
a1 - ones

array([0., 1., 2.])

In [7]:
# multiply - 1D array
a1 * ones

array([1., 2., 3.])

In [8]:
a2 = np.array([
     [1,2,3.3],
     [4,5,6.5]
 ])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
# multiply - 2D array
a1 * a2
# each element of a1 * each element of a2 in all rows

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [10]:
# numpy vectorizes code by broadcasting 

# so above codes are okay 

In [48]:
a1 / ones

array([1., 2., 3.])

In [49]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [50]:
# Floor division - removes the decimals
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [52]:
# power
a2 ** 2
# everything in a2 will be to the power of 2
# or

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [53]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [54]:
np.add(a1,ones) # same as a1+ones

array([2., 3., 4.])

In [55]:
a1 % 2 # return element-wise remainder of division

array([1, 0, 1], dtype=int32)

In [56]:
# exponent
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [57]:
# logarithm
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
# ------------------------------------------------------------

In [11]:
# The term broadcasting describes how numpy treats arrays with different shapes 
# during arithmetic operations

# Constraint: - smaller array is 'broadcast' across the larger array so that they
# have compatible shapes (not the other way around)

# i.e. 1D * 2D = okay
# i.e. 2D * 3D = not okay (they have different shapes, 3d has axis)

# errors that migh occur:- Value error due to broadcasting

In [12]:
a3 = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[1, 2, 3], [4, 5, 6]]
])
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### How can you reshape a2 to be compatible with a3

In [13]:
# Reshaping means changing the shape of an array.

# The shape of an array is the number of elements in each dimension.
# By reshaping we can change number (add/remove) of elements in each dimension.

In [19]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [20]:
# Reshape From 1-D to 2-D
a1.size

6

In [22]:
# a1 has 6 elements

# 6/2 = 3, so 3x2 or 2x3 2d array
re_shape = a1.reshape(2,3)
re_shape

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# Reshape From 1-D to 3-D
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
a1.size

12

In [25]:
# a1 has 12 elements
# 12/3 = 4
# (2,3,2) - outer will have 2 arrays, each with 3 arrays, containing 2 elements each

re_shape2 = a1.reshape(2,3,2)
re_shape2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [39]:
# Converting 2D to 3D
re_shape

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
re_shape.size

6

In [42]:
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you
re_shape3 = re_shape.reshape(2,1,-1)
re_shape3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [43]:
re_shape3.shape

(2, 1, 3)

In [58]:
# -------------------------------------------------------------------