In [4]:
import numpy as np
# import numpy library using np alias

## 1) Datatypes & Attributes of Numpy

In [5]:
# Numpy's main datatype is ndarray = n dimensional array

In [6]:
# 1-dimensonal array, also referred to as a vector
arr1 = np.array([1, 2, 3])
# accessing array function
# create a list of numbers

In [7]:
print(arr1) # for printing arr1

[1 2 3]


In [8]:
arr1 # or 2nd way in jupyter

array([1, 2, 3])

In [9]:
type(arr1) # checking type
# or print(type(arr1))

numpy.ndarray

In [10]:
# Dimensions in arrays 

# 2-dimensional array, also referred to as matrix
arr2 = np.array([
    [1,2.0,3.3],
    [4,5,6.5]
])

In [38]:
# 3-dimensional array, also referred to as a matrix
arr3 = np.array([
                [[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]
                ])

In [12]:
# accessing array index of 1d array
arr1[1]

2

In [13]:
# accessing array index of 2d array
arr2[0]
# displays first array(inner) on index 0 of outer array

array([1. , 2. , 3.3])

In [14]:
arr2[0][2] # accessing index 0 of outer array, index 0 has an array
# then access index 2 of inner array

3.3

### when you are opening the notebook again

you must start your code again from line 1
just press shift + enter 

In [15]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
# Shape of an Array = The shape of an array is the number of elements in each dimension.
# attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [18]:
arr1.shape

(3,)

In [19]:
arr2.shape
# (2,3) = 2 dimensions, each has 3 elements

(2, 3)

In [20]:
# Checking number of dimensions
# ndim attribute that returns an integer that tells us how many dimensions the array have

In [23]:
arr1.ndim, arr2.ndim, arr3.ndim
# arr1 = 1 dimension, arr2 = 2 dimension, etc...

(1, 2, 3)

In [24]:
# checking datatype of numpy array - dtype 
# checking size (no. of elements) of numpy array - size

In [25]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [26]:
arr1.size, arr2.size, arr3.size

(3, 6, 18)

### NOTE
although arr1, arr2, and arr3 vary in shapes
They are all ndarray ---> type

### Numpy forms the backbone of other ML packages

In [27]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### ML algorithms finds patterns in Numpy Arrays

In [28]:
# -----------------------------------------------------------------------

In [30]:
# Array containing strings
str_arr = np.array(['apple','orange','cherry'])
str_arr

array(['apple', 'orange', 'cherry'], dtype='<U6')

In [32]:
# Creating Arrays With a Defined Data Type
# using dtype
def_arr = np.array([1,2,3,4,5],dtype="S")
def_arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [33]:
# Converting Data Type on Existing Arrays
#ethod make a copy of the array with the astype() m
# specify the data type as a parameter. e.g. f for float, i for integer

In [34]:
# float to int
old_arr = np.array([1.1,3.4,2.5])
new_arr = old_arr.astype("i")
new_arr
new_arr.dtype

dtype('int32')

In [35]:
new_arr

array([1, 3, 2], dtype=int32)

In [37]:
# int to bool
bool_arr = new_arr.astype(bool)
bool_arr
# 1 or any number = True, 0 = False

array([ True,  True,  True])